### ISSUE TITLE
How do you keep your API Key secret?

### ISSUE THREAD

**Issue by judgej** [ideal-postcodes/jquery.postcodes#10]
Presumably anyone seeing your API key could use it to do their own lookups, having it charged to your account. Is there a way to keep it hidden, considering that it is in plain view in the JavaScript source?

I have only signed up for a developer key, and that does not get locked down to a specific URL. Perhaps the non-developer keys do, and I'm just not seeing that?

Perhaps there is a way to fetch temporary tokens from the server instead, given the API key, and use those for a small number of views (a dozen, say) and renewing them when they run out? Or is there some other mechanism?

**Comment by cblanc** [comment]
You can lock down to a specific URL(s) via the dashboard. Select your key, then select "settings".

We also recommend using the other limits (e.g. limits per IP address and total limits for the day)

**Comment by judgej** [comment]
Cool, that will sort it. Thanks.
